<?= $this->partial(sprintf("partial/%s/top-navigation", LAYOUT),[
    'a'=>"Admin",'b'=>$this->route,'c'=>$this->controller,'d'=>"ControleEstoque", "e"=>'editar']); ?>
<?=$this->Tab()->setInfoTitle("Manutenção do ControleEstoque")->tabPanel(
    $this->html('div')->setClass('col-md-12')->setText($this->html('div'))->appendText($this->render(sprintf("%s/editar-form", LAYOUT)))
)->nav("Geral")->render($this->html('section')->setClass('content'));