<?php
/**
 * Created by PhpStorm.
 * User: caltj
 * Date: 06/04/2018
 * Time: 16:23
 */

namespace Api\Filter;


use Admin\Entity\UserEntity;
use Core\Filter\AbstractFilter;
use Interop\Container\ContainerInterface;
use Zend\InputFilter\InputFilter;

class LoginFilter extends AbstractFilter
{

    /**
     * FilterInterface constructor.
     * @param ContainerInterface $container
     */
    public function __construct( ContainerInterface $container )
    {
        $this->container = $container;


    }

    public function getInputFilter()
    {
        if (!$this->inputFilter):
            $this->inputFilter = new InputFilter();

            $this->inputFilter->add([
                'name'=>'email',
                'required'=>true,
                'filters'=>$this->filters(),
                'validators'=>[
                    $this->RecordExists(UserEntity::class),
                    $this->StringLength('E-Mail'),
                    $this->NotEmpty('E-Mail'),
                ]
            ]);

            $this->inputFilter->add([
                'name'=>'password',
                'required'=>true,
                'filters'=>$this->filters(),
                'validators'=>[
                    $this->StringLength('Senha'),
                    $this->NotEmpty('Senha'),
                ]
            ]);


            $this->inputFilter->add([
                'name'=>'status',
                'required'=>false,
                'filters'=>$this->filters(),
                'validators'=>[]
            ]);


        endif;
        return parent::getInputFilter(); // TODO: Change the autogenerated stub
    }
}