<?php
/**
 * Created by PhpStorm.
 * User: caltj
 * Date: 26/03/2018
 * Time: 23:09
 */

namespace Api\Controller;


use Interop\Container\ContainerInterface;
use Zend\Mvc\Controller\AbstractRestfulController;
use Zend\View\Model\JsonModel;

abstract class ApiController extends AbstractRestfulController
{
    protected $container;
    /**
     * ApiController constructor.
     * @param ContainerInterface $container
     */
    abstract public function __construct(ContainerInterface $container);

    /**
     * @param mixed $data
     * @return mixed
     */
    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $id
     * @return mixed
     */
    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $id
     * @return mixed
     */
    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getList()
    {
        return new JsonModel(parent::getList()); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $id
     * @param mixed $data
     * @return mixed
     */
    public function update($id, $data)
    {
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }


}