<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-split">

        <li class="page-item <?=!isset($this->previous) ? ' disabled' : ''; ?>">
            <a class="page-link" data-page="<?php echo $this->first?>" href="">&laquo;</a></li>
        <li  class="page-item <?=!isset($this->previous) ? ' disabled' : ''; ?>">
            <a class="page-link" data-page="<?php echo $this->previous?>" href="">&lsaquo;</a></li>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <li  class="page-item <?php echo $page == $this->current ? 'active' : ''; ?>">
                <a class="page-link" data-page="<?php echo $page?>" href="">
                    <?php echo $page; ?>
                </a>
            </li>
        <?php endforeach; ?>
        <!-- Next page link -->
        <li  class="page-item <?=!isset($this->next) ? ' disabled' : ''; ?>">
            <a class="page-link" data-page="<?php echo $this->next?>" href="">&rsaquo;</a></li>
        <!-- Last page link -->
        <li class="page-item <?=!isset($this->next) ? ' disabled' : ''; ?>">
            <a class="page-link" data-page="<?php echo $this->last?>" href="">&raquo;</a></li>
    </ul>
<?php endif; ?>
