<label class="sr-only" for="inlineFormInputGroup">Username</label>
<div class="input-group mb-2">
    <div class="input-group-prepend">
        <div id="inlineFormInputGroup" class="input-group-text"><i class="fa fa-search"></i></div>
    </div>
    <input name="table_search"  type="text" class="form-control quick-search" id="inlineFormInputGroup" placeholder="Search" value="<?=$this->quickSearch?>">
</div>