
<!-- ============================================================= SECTION – HERO ============================================================= -->

<section id="hero" class="img-bg-bottom img-bg-soft tint-bg" style="background-image: url(<?=$this->basePath("assets-vodka-everest/images/art/slider03.jpg")?>);">
    <div class="container inner">
        <div class="row">
            <div class="col-sm-10">
                <header>
                    <h1>Hi, we are REEN — <br>digital creatives</h1>
                </header>
            </div><!-- /.col -->
        </div><!-- ./row -->
    </div><!-- /.container -->
</section>

<!-- ============================================================= SECTION – HERO : END ============================================================= -->


<!-- ============================================================= SECTION – WHO WE ARE ============================================================= -->

<section id="who-we-are">
    <div class="container inner-md">
        <div class="row inner-top-xs">

            <div class="col-sm-6 inner-right-xs inner-bottom-xs">
                <h2>Who we are</h2>
                <p>Magnis modipsae que lib voloratati andigen daepeditem quiate ut reporemni aut labor. Laceaque quiae sitiorem rest non restibusaes es tumquam core posae volor remped modis volor. Doloreiur qui commolu ptatemp dolupta oreprerum tibusam. Eumenis et consent accullignis dentibea autem inisita posae volor conecus resto explabo.</p>
            </div><!-- /.col -->

            <div class="col-sm-6 inner-left-xs inner-bottom-xs">
                <h2>What we do</h2>
                <p>Laceaque quiae sitiorem rest non restibusaes es tumquam core posaeremni volor remped modis volor. Doloreiur qui commolu dolor oreprerum tibusam. Eumenis et consent accullignis dentibea autem inisita posae volor conecus resto explabo. Magnis modipsae que lib voloratati andigen daepeditem quiate ut reporemni aut labor.</p>
            </div><!-- /.col -->

        </div><!-- /.row -->
    </div><!-- /.container -->
</section>

<!-- ============================================================= SECTION – WHO WE ARE : END ============================================================= -->



<!-- ============================================================= SECTION – TEAM : END ============================================================= -->



<!-- ============================================================= SECTION – TESTIMONIALS ============================================================= -->

<section id="testimonials" class="light-bg img-bg-softer" style="background-image: url(<?=$this->basePath("assets-vodka-everest/images/art/pattern-background01.jpg")?>);">
    <div class="container inner">

        <div class="row">
            <div class="col-md-5 col-sm-8 center-block text-center">
                <header>
                    <h1>What clients are saying about us</h1>
                </header>
            </div><!-- /.col -->
        </div><!-- /.row -->

        <div class="row">
            <div class="col-md-8 col-sm-9 center-block text-center">
                <div id="owl-testimonials" class="owl-carousel owl-outer-nav owl-ui-md">

                    <div class="item">
                        <blockquote>
                            <p>Need a professional kickass looking portfolio template, REEN is the way to go! It is simple, beautiful and really easy to use. Great product!</p>
                            <footer>
                                <cite>Steve Gates</cite>
                            </footer>
                        </blockquote>
                    </div><!-- /.item -->

                    <div class="item">
                        <blockquote>
                            <p>REEN is a sleek, beautiful, ridiculously easy to use multipurpose template. More importantly, it’s a huge time saver for busy creatives!</p>
                            <footer>
                                <cite>Amber Jones</cite>
                            </footer>
                        </blockquote>
                    </div><!-- /.item -->

                    <div class="item">
                        <blockquote>
                            <p>Been putting off creating my portfolio for several years, then I found REEN and about 30 minutes later ... I have an awesome looking portfolio. Totally love it!</p>
                            <footer>
                                <cite>Bill Jobs</cite>
                            </footer>
                        </blockquote>
                    </div><!-- /.item -->

                </div><!-- /.owl-carousel -->
            </div><!-- /.col -->
        </div><!-- /.row -->

    </div><!-- /.container -->
</section>

<!-- ============================================================= SECTION – TESTIMONIALS : END ============================================================= -->


<!-- ============================================================= SECTION – GET IN TOUCH ============================================================= -->

<section id="get-in-touch" class="tint-bg">
    <div class="container inner-sm">
        <div class="row">
            <div class="col-sm-10 center-block text-center">
                <h1 class="single-block">Want to work with us? <a href="#" class="btn btn-large">Get in touch</a></h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>

<!-- ============================================================= SECTION – GET IN TOUCH : END ============================================================= -->