<?php
$collums08[] = $this->El()->hidden('id')->hidden('empresa')
    ->setClass('col-md-6 col-xs-12')
    ->input('first_name')
    ->input('last_name')
    ->render($this->html('div')->setClass('row'));

$collums08[] = $this->El()
    ->setClass('col-md-6 col-xs-12')
    ->input('email')
    ->input('password')
    ->render($this->html('div')->setClass('row'));

$collums08[] = $this->El()
    ->setClass('col-md-4 col-xs-12')
    ->input('facebook')
    ->input('google')
    ->input('twitter')
    ->render($this->html('div')->setClass('row'));

$collums08[] = $this->El()->input('description')->render($this->html('div')->setClass('row'));


$collums04[] =   $this->html('div')->setClass('row')->setText(
    $this->El()->file()->render($this->html('div')->setClass('col-md-12'))
);


$collums04[] = $this->El()->setClass('col-md-12')
    ->timepicker('created_at')
    ->timepicker('updated_at')
    ->input('status')
    ->render($this->html('div')->setClass('row'));

$html[] = $this->html('div')->setClass('row')->setText(
    $this->html('div')->setClass('col-md-8 col-xs-12')->setText(implode("", $collums08))
)->appendText(
    $this->html('div')->setClass('col-md-4 col-xs-12')->setText(implode("", $collums04))
);
$actions[] =   $this->Actions()
    ->submit()
    ->save_copy()
    ->save_close()
    ->back()
    ->render($this->html('div')->setClass('row'));
?>

<?= $this->partial(sprintf("/layout/%s/partial/create", LAYOUT), [
    'body' => implode("", $html),
    'actions' => implode("", $actions),
    'form' => $this->form,
    'route' => $this->route,
    'controller' => $this->controller,
]); ?>