<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title"><?=$this->title?></h4>
        </div>
        <div class="modal-body">
            <?=$this->body?>
        </div>
        <div class="modal-footer">
            <?=$this->footer?>
        </div>
    </div>
</div>