<?= $this->partial(sprintf('layout/%s/partial/form-error', LAYOUT), ['form' => $this->form]); ?>
<?= $this->form()->openTag($this->form->setAttribute('action', $this->url(sprintf("%s/default", $this->route), [
    'controller' => $this->controller,
    'action' => 'upload'
]))->setAttribute('name', 'AjaxUploadForm')->setAttribute('class', 'modal fade in')->setAttribute('id', 'modal-default')); ?>
<?php
$this->form->get('parent')->setValue($this->parent);
$this->form->get('assets')->setValue($this->assets);

$html1[] = $this->html('img')->setAttributes([
    'id' => 'file',
    'data-cover' => $this->basePath($this->form->get('cover')->getValue()),
    'class' => 'attachment rounded-circle img-thumbnail',
    'alt' => 'ser profile picture',
    'src' => $this->url(sprintf("%s/default", $this->route), ['controller' => $this->controller, 'action' => 'file'],
        ['query' => [
            'name' => $this->basePath($this->form->get('cover')->getValue()),
            'thumbnail' => true,
            'w' => $this->form->get('cover_width')->getValue(),
        ]
        ]),
]);

$html1[] =  $this->html('div')->setClass('btn btn-default btn-warning btn-file btn-block')->setText(
    $this->html('i')->setClass('fa fa-paperclip')
)
    ->appendText($this->html('input')->setAttributes([
        'name' => 'file',
        'type' => 'file',
    ]))
    ->appendText('Selecione uma imagem');

$html2[] = $this->html('div')->setClass('text-left m-t-0')->setText(
    $this->El()->hidden('id')->hidden('empresa')
        ->hidden('assets')
        ->input('status')
        ->hidden('parent')
        ->setClass('col-md-12')
        ->input('name')
        ->render($this->html('div')->setClass('row'))
);
$html2[] = $this->html('div')->setClass('text-left m-t-0')->setText(
    $this->El()
        ->setClass('col-md-4')
        ->input('cover_width')
        ->input('cover_height')
        ->input('cover_quality')
        ->render($this->html('div')->setClass('row'))
);

$html2[] =  $this->html('div')->setClass('text-left m-t-0')->setText(
    $this->El()
        ->setClass('col-md-12')
        ->input('description')
        ->render($this->html('div')->setClass('row'))
);


$html1[] =  $this->html('div')->setAttributes([
    'class' => 'progress',
])->setText(
    $this->html('div')->setAttributes([
        'id' => 'upload-progress',
        'class' => 'progress-bar progress-bar-primary progress-bar-striped',
        'role' => 'progressbar',
        'aria-valuenow' => '40',
        'aria-valuemin' => '0',
        'aria-valuemax' => '100',
    ])->setText($this->html('span')->setAttributes([
        'class' => 'sr-only',
        'style' => "min-width: 2em;"
    ])->setText(''))
);

$html3[] = $this->html('div')->setClass('member-card')->setText(implode('',$html1));
$html4[] = $this->html('div')->setClass('member-card')->setText(implode('',$html2));

?>
    <div class="modal-dialog">
        <div class="modal-content">
            <?= $this->html('div')->setClass('modal-header')->setText('Upload de imagens') ?>
            <?= $this->html('div')->setClass('modal-body')->setText(
                $this->html('div')->setClass('text-center card-box')
                    ->setText(
                         $this->Tab()->setNumber(5)
                        ->setInfoTitle("Manutenção dos menus")->tabPanel(implode('',$html1))->tabPanel(implode('',$html2))
                        ->nav("Geral")
                        ->nav("Setings")
                        ->render())
            ) ?>
            <?= $this->html('div')->setClass('modal-footer')->setText($this->Actions()
                ->dismiss(5)
                ->upload(7)
                ->render($this->html('div')->setClass('row'))) ?>
        </div>
    </div>
<?= $this->form()->closeTag(); ?>