<!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="<?= $this->url("admin") ?>" class="logo"><i class="mdi mdi-radar"></i> <span><?= getenv('ADMIN_NAME') ?></span></a>
        </div>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <nav class="navbar-custom">

        <ul class="list-inline float-right mb-0">

            <li class="list-inline-item notification-list hide-phone">
                <a class="nav-link waves-light waves-effect" href="#" id="btn-fullscreen">
                    <i class="mdi mdi-crop-free noti-icon"></i>
                </a>
            </li>

            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <img src="<?= $this->basePath($this->identity()->getCover()) ?>" alt="user" class="rounded-circle">
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown " aria-labelledby="Preview">
                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5 class="text-overflow"><small>Welcome !  <?= $this->identity()->getFirstName() ?> <?= $this->identity()->getLastName() ?> </small> </h5>
                    </div>

                    <!-- item-->
                    <a href="<?= $this->url("adm-admin/default", [
                        'controller' => 'user',
                        'action' => 'profile'
                    ]) ?>" class="dropdown-item notify-item">
                        <i class="mdi mdi-account"></i> <span><?= $this->translate('Profile') ?></span>
                    </a>

                    <!-- item-->
                    <a href="<?= $this->url("adm-auth-sair") ?>" class="dropdown-item notify-item">
                        <i class="mdi mdi-settings"></i> <span><?=$this->translate('Settings')?></span>
                    </a>

                    <!-- item-->
                    <a href="<?= $this->url("adm-auth-sair") ?>" class="dropdown-item notify-item">
                        <i class="mdi mdi-lock-open"></i> <span><?=$this->translate('Lock Screen')?></span>
                    </a>

                    <!-- item-->
                    <a href="<?= $this->url("adm-auth-sair") ?>" class="dropdown-item notify-item">
                        <i class="mdi mdi-logout"></i> <span><?=$this->translate('Logout')?></span>
                    </a>

                </div>
            </li>

        </ul>

        <ul class="list-inline menu-left mb-0">
            <li class="float-left">
                <button class="button-menu-mobile open-left waves-light waves-effect">
                    <i class="mdi mdi-menu"></i>
                </button>
            </li>

        </ul>

    </nav>

</div>
<!-- Top Bar End -->