<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li class="menu-title">Main</li>

                <li>
                    <a href="<?= $this->url("adm-admin") ?>" class="waves-effect waves-primary"><i
                                class="ti-home"></i><span> <?= $this->translate('Dashboard') ?> </span></a>
                </li>
                <?php
                /* @var $container Zend\Navigation\Navigation */
                $container = $this->container;
                if ($container):?>
                    <?php foreach ($container as $page): ?>
                        <?php if (!$this->navigation()->accept($page)) continue; ?>
                        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
                        <?php $hasChildren = $page->hasPages() ?>
                        <?php
                        if ($hasChildren):
                            //check if access is allowed at least one item
                            $access = false;
                            foreach ($page->getPages() as $child) {
                                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                                    $access = true;
                                }
                            }
                            if ($access) :
                                ?>
                                <li class="has_sub <?php if ($page->isActive(true)) echo ' active' ?>">
                                    <a href="#">
                                        <?php if ($page->get("icone") !== ""): ?>
                                            <i class="<?= $page->get("icone"); ?>"></i>
                                        <?php endif; ?>
                                        <span>
                                <?= $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>

                                    </a>
                                    <ul class="list-unstyled">
                                        <?php foreach ($page->getPages() as $child): ?>
                                            <?php if (!$this->navigation()->accept($child)) continue; ?>
                                            <?php if ($child->get("separator") === true): ?>
                                                <li class="divider"></li>
                                                <?php
                                                continue;
                                            endif;
                                            ?>
                                            <li class="<?= $child->isActive(true) ? 'active' : '' ?>">
                                                <a href="<?= $child->getHref(); ?>"
                                                    <?php if ($child->getTarget() != ""): ?>
                                                        target="<?= $child->getTarget(); ?>"
                                                    <?php endif; ?> >
                                                    <?php if ($child->get("icone") !== ""): ?>
                                                        <i class="<?= $child->get("icone"); ?>"></i>
                                                    <?php endif; ?>
                                                    <span><?= $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>
                                                </a>
                                            </li>
                                        <?php endforeach ?>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        <?php else: ?>
                            <li class="<?= $page->isActive() ? ' active' : '' ?>">
                                <a href="<?= $page->getHref() ?>"
                                    <?php if ($page->getTarget() != ""): ?>
                                        target="<?php echo $page->getTarget(); ?>"
                                    <?php endif; ?> >
                                    <?php if ($page->get("icone") !== ""): ?>
                                        <i class="<?= $page->get("icone"); ?>"></i>
                                    <?php endif; ?>
                                    <span><?= $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>
                                </a>
                            </li>

                        <?php endif ?>
                    <?php endforeach ?>

                <?php
                endif;
                ?>
                <li class="menu-title">Configurações</li>
                <li><a href="<?= $this->url("adm-make") ?>"  class="waves-effect waves-primary"><i class="fa fa-magic"></i>
                        <span><?= $this->translate('Makes') ?></span></a></li>

                <li><a href="<?= $this->url("adm-config") ?>" class="waves-effect waves-primary"><i class="fa fa-gear"></i>
                        <span><?= $this->translate('Configuração') ?></span></a>

                </li>

                <li><a href="<?= $this->url("adm-admin/default", [
                        'controller' => 'user',
                        'action' => 'profile'
                    ]) ?>" class="waves-effect waves-primary"><i class="fa fa-user"></i> <span><?= $this->translate('Profile') ?></span></a></li>
                <li><a href="<?= $this->url("adm-auth-sair") ?>" class="waves-effect waves-primary"><i class="fa fa-sign-out"></i>
                        <span><?= $this->translate('Sign out') ?></span></a></li>
            </ul>

            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End -->

