<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title"><?=Core\Module::SIS?></h4>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><a href="<?=$this->url('admin')?>">Admin</a></li>
                <li class="breadcrumb-item"><a href="<?=$this->url($this->b, [
                        'controller'=>$this->c
                    ])?>"><?=$this->d?></a></li>
                <li class="breadcrumb-item active"><?=$this->e?></li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>