<div class="container">
    <div class="text-center m-t-20">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h2 class="title zoomIn animated wow" data-wow-delay=".1s">Todas as Solicitações</h2>
                <p class="sub-title zoomIn animated wow" data-wow-delay=".2s">Lista com todas as solicitações.</p>
            </div>
        </div>
    </div>
</div>
    <div class="m-l-15 m-r-15 m-b-5">
        <div class="row">
            <div class="col-sm-12">
                <div id="tableContainer"  style="position: relative;min-height: 500px">
                    <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 85%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <script>
                    $("#tableContainer").zfTable('<?=$this->url("home-solicitacoes/default",['controller'=>'solicitacao', 'action'=>'all'])?>');
                </script>
                <hr>
                <div class="m-3">
                    <a href="<?=$this->url('home-client')?>" class="btn btn-success btn-rounded w-lg animated fadeInDown wow" data-wow-delay=".4s">Voltar para minha conta</a>
                    <a href="<?=$this->url('home')?>" class="btn btn-primary btn-rounded w-lg animated fadeInDown wow" data-wow-delay=".4s">Voltar para a inicio</a>
                </div>
            </div>
        </div>
        <!-- end: col -->
        <?= $this->partial(sprintf('layout/%s/partial/messages', LAYOUT)); ?>
    </div>
