<?php

namespace Blog\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieBlogRepository extends EntityRepository
{
}
