<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle("VODKA-EVEREST")->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets-vodka-everrest/images/favicon.ico'])
        ->prependStylesheet($this->basePath('assets-vodka-everrest/fonts/fontello.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everrest/css/animate.min.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everrest/css/owl.transitions.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everrest/css/owl.carousel.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everrest/css/blue.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everrest/css/main.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everrest/css/bootstrap.min.css'))
        ->prependStylesheet('//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic')
        ->prependStylesheet('//fonts.googleapis.com/css?family=Lato:400,900,300,700')
    ?>
</head>
<body>

<!-- ============================================================= HEADER ============================================================= -->

<header>
    <div class="navbar">

        <div class="navbar-header">
            <div class="container">

                <ul class="info pull-left">
                    <li><a href="#"><i class="icon-mail-1 contact"></i> info@reen.com</a></li>
                    <li><i class="icon-mobile contact"></i> +00 (123) 456 78 90</li>
                </ul><!-- /.info -->

                <ul class="social pull-right">
                    <li><a href="#"><i class="icon-s-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-s-gplus"></i></a></li>
                    <li><a href="#"><i class="icon-s-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
                    <li><a href="#"><i class="icon-s-behance"></i></a></li>
                    <li><a href="#"><i class="icon-s-dribbble"></i></a></li>
                </ul><!-- /.social -->

                <!-- ============================================================= LOGO MOBILE ============================================================= -->

                <a class="navbar-brand" href="index.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/logo.svg")?>" class="logo" alt=""></a>

                <!-- ============================================================= LOGO MOBILE : END ============================================================= -->

                <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a>

            </div><!-- /.container -->
        </div><!-- /.navbar-header -->

        <div class="yamm">
            <div class="navbar-collapse collapse">
                <div class="container">

                    <!-- ============================================================= LOGO ============================================================= -->

                    <a class="navbar-brand" href="index.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/logo.svg")?>" class="logo" alt=""></a>

                    <!-- ============================================================= LOGO : END ============================================================= -->


                    <!-- ============================================================= MAIN NAVIGATION ============================================================= -->

                    <ul class="nav navbar-nav">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle js-activated">Home</a>

                            <ul class="dropdown-menu">
                                <li><a href="index.html">Agency Style</a></li>
                                <li><a href="index2.html">Product Style</a></li>
                                <li><a href="index3.html">Service Style</a></li>
                                <li><a href="index4.html">Portfolio Style</a></li>
                                <li><a href="index5.html">Showcase Style</a></li>
                            </ul><!-- /.dropdown-menu -->
                        </li><!-- /.dropdown -->

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle js-activated">Portfolio</a>

                            <ul class="dropdown-menu">
                                <li><a href="portfolio.html">3 Columns Grid</a></li>
                                <li><a href="portfolio2.html">3 Columns Details Grid</a></li>
                                <li><a href="portfolio3.html">4 Columns Grid</a></li>
                                <li><a href="portfolio4.html">4 Columns Details Grid</a></li>
                                <li><a href="portfolio5.html">Fullscreen Grid</a></li>
                                <li><a href="portfolio-post.html">Post with Slider I</a></li>
                                <li><a href="portfolio-post2.html">Post with Slider II</a></li>
                                <li><a href="portfolio-post3.html">Post with Images I</a></li>
                                <li><a href="portfolio-post4.html">Post with Images II</a></li>
                                <li><a href="portfolio-post5.html">Post with Video</a></li>
                                <li><a href="portfolio-post6.html">Post with Audio</a></li>
                            </ul><!-- /.dropdown-menu -->
                        </li><!-- /.dropdown -->

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle js-activated">Blog</a>

                            <ul class="dropdown-menu">
                                <li><a href="blog.html">Sidebar right</a></li>
                                <li><a href="blog2.html">Sidebar left</a></li>
                                <li><a href="blog3.html">Without Sidebar</a></li>
                                <li><a href="blog4.html">2 Columns Grid Sidebar right</a></li>
                                <li><a href="blog5.html">2 Columns Grid Sidebar left</a></li>
                                <li><a href="blog6.html">2 Columns Grid without Sidebar</a></li>
                                <li><a href="blog7.html">3 Columns Grid without Sidebar</a></li>
                                <li><a href="blog-post.html">Post Sidebar right</a></li>
                                <li><a href="blog-post2.html">Post Sidebar left</a></li>
                                <li><a href="blog-post3.html">Post without Sidebar</a></li>
                            </ul><!-- /.dropdown-menu -->
                        </li><!-- /.dropdown -->

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle js-activated">Pages</a>

                            <ul class="dropdown-menu">
                                <li><a href="about.html">About I</a></li>
                                <li><a href="about2.html">About II</a></li>
                                <li><a href="services.html">Services I</a></li>
                                <li><a href="services2.html">Services II</a></li>
                                <li><a href="services3.html">Services III</a></li>
                                <li><a href="pricing.html">Pricing I</a></li>
                                <li><a href="pricing2.html">Pricing II</a></li>
                                <li><a href="sidenav.html">Side Navigation</a></li>
                            </ul><!-- /.dropdown-menu -->
                        </li><!-- /.dropdown -->

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle js-activated">Features</a>

                            <ul class="dropdown-menu">

                                <li><a href="slider-carousel.html">Slider/Carousel</a></li>
                                <li><a href="tab.html">Tab</a></li>
                                <li><a href="accordion.html">Accordion</a></li>
                                <li><a href="isotope.html">Isotope</a></li>
                                <li><a href="styles.html">Styles</a></li>
                                <li><a href="font-icons.html">Font Icons</a></li>
                                <li><a href="backgrounds.html">Backgrounds</a></li>

                                <li class="dropdown-submenu">
                                    <a href="#">Colors</a>

                                    <ul class="dropdown-menu">
                                        <li><a class="changecolor green" title="Green color">Green</a></li>
                                        <li><a class="changecolor blue" title="Blue color">Blue</a></li>
                                        <li><a class="changecolor red" title="Red color">Red</a></li>
                                        <li><a class="changecolor pink" title="Pink color">Pink</a></li>
                                        <li><a class="changecolor purple" title="Purple color">Purple</a></li>
                                        <li><a class="changecolor orange" title="Orange color">Orange</a></li>
                                        <li><a class="changecolor navy" title="Navy color">Navy</a></li>
                                        <li><a class="changecolor gray" title="Gray color">Gray</a></li>
                                    </ul><!-- /.dropdown-menu -->
                                </li><!-- /.dropdown-submenu -->

                                <li class="dropdown-submenu">
                                    <a href="#">Submenu Levels</a>

                                    <ul class="dropdown-menu">
                                        <li><a href="#">Second Level</a></li>
                                        <li><a href="#">Second Level</a></li>

                                        <li class="dropdown-submenu">
                                            <a href="#">More</a>

                                            <ul class="dropdown-menu">
                                                <li><a href="#">Third Level</a></li>
                                                <li><a href="#">Third Level</a></li>
                                            </ul><!-- /.dropdown-menu -->
                                        </li><!-- /.dropdown-submenu -->
                                    </ul><!-- /.dropdown-menu -->
                                </li><!-- /.dropdown-submenu -->

                            </ul><!-- /.dropdown-menu -->
                        </li><!-- /.dropdown -->

                        <!-- ============================================================= MEGA MENU ============================================================= -->

                        <li class="dropdown yamm-fullwidth">
                            <a href="#" class="dropdown-toggle js-activated">Mega Menu</a>

                            <ul class="dropdown-menu yamm-dropdown-menu">
                                <li>
                                    <div class="yamm-content row">

                                        <div class="col-sm-3 inner">
                                            <h4>Focus on</h4>
                                            <figure>
                                                <div class="icon-overlay icn-link">
                                                    <a href="portfolio-post.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/art/work01.jpg")?>" alt=""></a>
                                                </div>
                                                <figcaption>
                                                    <p>Consed quodips ameniat empernam que apid cust quas molor eatis numa estio.</p>
                                                    <a href="portfolio-post.html" class="btn">View Project</a>
                                                </figcaption>
                                            </figure>
                                        </div><!-- /.col -->

                                        <div class="col-sm-3 inner">
                                            <h4>Special Pages</h4>

                                            <ul class="circled">
                                                <li><a href="portfolio2.html">3 Columns Details Grid Portfolio</a></li>
                                                <li><a href="portfolio5.html">Fullscreen Grid Portfolio</a></li>
                                                <li><a href="portfolio-post5.html">Portfolio Post with Video</a></li>
                                                <li><a href="blog5.html">2 Columns Grid Blog with Left Sidebar</a></li>
                                                <li><a href="blog7.html">3 Columns Grid Blog without Sidebar</a></li>
                                                <li><a href="blog-post.html">Blog Post with Right Sidebar</a></li>
                                                <li><a href="sidenav.html">Side Navigation Page</a></li>
                                                <li><a href="about2.html">About Page II</a></li>
                                                <li><a href="services.html">Service Page I</a></li>
                                                <li><a href="pricing.html">Pricing Page I</a></li>
                                                <li><a href="contact.html">Contact Page I</a></li>
                                            </ul><!-- /.circled -->
                                        </div><!-- /.col -->

                                        <div class="col-sm-3 inner">
                                            <h4>Latest Works</h4>

                                            <div class="row thumbs gap-xs">

                                                <div class="col-xs-6 thumb">
                                                    <figure class="icon-overlay icn-link">
                                                        <a href="portfolio-post.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/art/work02.jpg")?>" alt=""></a>
                                                    </figure>
                                                </div><!-- /.thumb -->

                                                <div class="col-xs-6 thumb">
                                                    <figure class="icon-overlay icn-link">
                                                        <a href="portfolio-post.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/art/work03.jpg")?>" alt=""></a>
                                                    </figure>
                                                </div><!-- /.thumb -->

                                                <div class="col-xs-6 thumb">
                                                    <figure class="icon-overlay icn-link">
                                                        <a href="portfolio-post.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/art/work04.jpg")?>" alt=""></a>
                                                    </figure>
                                                </div><!-- /.thumb -->

                                                <div class="col-xs-6 thumb">
                                                    <figure class="icon-overlay icn-link">
                                                        <a href="portfolio-post.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/art/work05.jpg")?>" alt=""></a>
                                                    </figure>
                                                </div><!-- /.thumb -->

                                                <div class="col-xs-6 thumb">
                                                    <figure class="icon-overlay icn-link">
                                                        <a href="portfolio-post.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/art/work06.jpg")?>" alt=""></a>
                                                    </figure>
                                                </div><!-- /.thumb -->

                                                <div class="col-xs-6 thumb">
                                                    <figure class="icon-overlay icn-link">
                                                        <a href="portfolio-post.html"><img src="<?= $this->basePath("assets-vodka-everrest/images/art/work07.jpg")?>" alt=""></a>
                                                    </figure>
                                                </div><!-- /.thumb -->

                                            </div><!-- /.row -->
                                        </div><!-- /.col -->

                                        <div class="col-sm-3 inner">
                                            <h4>About Us</h4>
                                            <p>Voluptat ibusaped molorporro consequ idustibus. Reressi morum ut dolessiti tem nihicid ernatum, coria volore non pro officat ut autem accaborem conet. Omnis peribus qui dolent praeperrum coria.</p>
                                            <p>Equam conesti occum dolorest, quae venderes quistius, comnitatur sae dinam nonseculpa cum fugit is verciam.</p>
                                            <a href="about.html" class="btn">Read More</a>
                                        </div><!-- /.col -->

                                    </div><!-- /.yamm-content -->
                                </li>
                            </ul><!-- /.yamm-dropdown-menu -->
                        </li><!-- /.yamm-fullwidth -->

                        <!-- ============================================================= MEGA MENU : END ============================================================= -->

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle js-activated">Contact</a>

                            <ul class="dropdown-menu">
                                <li><a href="contact.html">Contact I</a></li>
                                <li><a href="contact2.html">Contact II</a></li>
                                <li><a href="contact3.html">Contact III</a></li>
                            </ul><!-- /.dropdown-menu -->
                        </li><!-- /.dropdown -->

                        <li class="dropdown pull-right searchbox">
                            <a href="#" class="dropdown-toggle js-activated"><i class="icon-search"></i></a>

                            <div class="dropdown-menu">
                                <form id="search" class="navbar-form search" role="search">
                                    <input type="search" class="form-control" placeholder="Type to search">
                                    <button type="submit" class="btn btn-default btn-submit icon-right-open"></button>
                                </form>
                            </div><!-- /.dropdown-menu -->
                        </li><!-- /.searchbox -->

                    </ul><!-- /.nav -->

                    <!-- ============================================================= MAIN NAVIGATION : END ============================================================= -->

                </div><!-- /.container -->
            </div><!-- /.navbar-collapse -->
        </div><!-- /.yamm -->
    </div><!-- /.navbar -->
</header>

<!-- ============================================================= HEADER : END ============================================================= -->


<!-- ============================================================= MAIN ============================================================= -->

<main>
<?= $this->content ?>
</main>
<!-- ============================================================= FOOTER ============================================================= -->

<footer class="dark-bg">
    <div class="container inner">
        <div class="row">

            <div class="col-md-3 col-sm-6 inner">
                <h4>Who we are</h4>
                <a href="index.html"><img class="logo img-intext" src="<?= $this->basePath("assets-vodka-everrest/images/logo-white.svg")?>" alt=""></a>
                <p>Magnis modipsae voloratati andigen daepeditem quiate re porem que aut labor. Laceaque eictemperum
                    quiae sitiorem rest non restibusaes maio es dem tumquam.</p>
                <a href="about.html" class="txt-btn">More about us</a>
            </div><!-- /.col -->

            <div class="col-md-3 col-sm-6 inner">
                <h4>Latest works</h4>

                <div class="row thumbs gap-xs">

                    <div class="col-xs-6 thumb">
                        <figure class="icon-overlay icn-link">
                            <a href="portfolio-post.html"><img
                                        src="<?= $this->basePath("assets-vodka-everrest/images/art/work02.jpg") ?>"
                                        alt=""></a>
                        </figure>
                    </div><!-- /.thumb -->

                    <div class="col-xs-6 thumb">
                        <figure class="icon-overlay icn-link">
                            <a href="portfolio-post.html"><img
                                        src="<?= $this->basePath("assets-vodka-everrest/images/art/work03.jpg") ?>"
                                        alt=""></a>
                        </figure>
                    </div><!-- /.thumb -->

                    <div class="col-xs-6 thumb">
                        <figure class="icon-overlay icn-link">
                            <a href="portfolio-post.html"><img
                                        src="<?= $this->basePath("assets-vodka-everrest/images/art/work07.jpg") ?>"
                                        alt=""></a>
                        </figure>
                    </div><!-- /.thumb -->

                    <div class="col-xs-6 thumb">
                        <figure class="icon-overlay icn-link">
                            <a href="portfolio-post.html"><img
                                        src="<?= $this->basePath("assets-vodka-everrest/images/art/work01.jpg") ?>"
                                        alt=""></a>
                        </figure>
                    </div><!-- /.thumb -->

                </div><!-- /.row -->
            </div><!-- /.col -->


            <div class="col-md-3 col-sm-6 inner">
                <h4>Get In Touch</h4>
                <p>Doloreiur quia commolu ptatemp dolupta oreprerum tibusam eumenis et consent accullignis dentibea
                    autem inisita.</p>
                <ul class="contacts">
                    <li><i class="icon-location contact"></i> 84 Street, City, State 24813</li>
                    <li><i class="icon-mobile contact"></i> +00 (123) 456 78 90</li>
                    <li><a href="#"><i class="icon-mail-1 contact"></i> info@reen.com</a></li>
                </ul><!-- /.contacts -->
            </div><!-- /.col -->

            <div class="col-md-3 col-sm-6 inner">
                <h4>Free updates</h4>
                <p>Conecus iure posae volor remped modis aut lor volor accabora incim resto explabo.</p>
                <form id="newsletter" class="form-inline newsletter" role="form">
                    <label class="sr-only" for="exampleInputEmail">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail"
                           placeholder="Enter your email address">
                    <button type="submit" class="btn btn-default btn-submit">Subscribe</button>
                </form>
            </div><!-- /.col -->

        </div><!-- /.row -->
    </div><!-- .container -->

    <div class="footer-bottom">
        <div class="container inner">
            <p class="pull-left">© 2014 REEN. All rights reserved.</p>
            <ul class="footer-menu pull-right">
                <li><a href="index.html">Home</a></li>
                <li><a href="portfolio.html">Portfolio</a></li>
                <li><a href="blog.html">Blog</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="services.html">Services</a></li>
                <li><a href="contact.html">Contact</a></li>
            </ul><!-- .footer-menu -->
        </div><!-- .container -->
    </div><!-- .footer-bottom -->
</footer>
<!-- END FAQ -->
<!-- JavaScripts placed at the end of the document so the pages load faster -->

<!-- Scripts -->
<?= $this->inlineScript()
    ->appendFile($this->basePath("assets-vodka-everrest/js/jquery.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/jquery.easing.1.3.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/bootstrap.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/bootstrap-hover-dropdown.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/skrollr.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/skrollr.stylesheets.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/waypoints.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/waypoints-sticky.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/owl.carousel.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/jquery.isotope.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/jquery.easytabs.min.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/jquery.slickforms.js"))
    //->appendFile($this->basePath("assets-vodka-everrest/js/google.maps.api.v3.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/viewport-units-buggyfill.js"))
    ->appendFile($this->basePath("assets-vodka-everrest/js/scripts.js"))
?>

</body>
</html>
