<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle("VODKA-EVEREST")->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets-vodka-everest/images/favicon.ico'])
        ->prependStylesheet($this->basePath('assets-vodka-everest/css/blue.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everest/css/owl.carousel.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everest/fonts/fontello.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everest/css/animate.min.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everest/css/owl.transitions.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everest/css/main.css'))
        ->prependStylesheet($this->basePath('assets-vodka-everest/css/bootstrap.min.css'))
        ->prependStylesheet('//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic')
        ->prependStylesheet('//fonts.googleapis.com/css?family=Lato:400,900,300,700')
    ?>
</head>
<body>
<!-- ============================================================= HEADER ============================================================= -->
<header>
    <div class="navbar">

        <div class="navbar-header">
            <div class="container">

                <ul class="info pull-left">
                    <li><a href="#"><i class="icon-mail-1 contact"></i> info@reen.com</a></li>
                    <li><i class="icon-mobile contact"></i> +00 (123) 456 78 90</li>
                </ul><!-- /.info -->

                <ul class="social pull-right">
                    <li><a href="#"><i class="icon-s-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-s-gplus"></i></a></li>
                    <li><a href="#"><i class="icon-s-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
                    <li><a href="#"><i class="icon-s-behance"></i></a></li>
                    <li><a href="#"><i class="icon-s-dribbble"></i></a></li>
                </ul><!-- /.social -->

                <!-- ============================================================= LOGO MOBILE ============================================================= -->

                <a class="navbar-brand" href="index.html"><img src="<?= $this->basePath("assets-vodka-everest/images/logo.svg")?>" class="logo" alt=""></a>

                <!-- ============================================================= LOGO MOBILE : END ============================================================= -->

                <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a>

            </div><!-- /.container -->
        </div><!-- /.navbar-header -->

        <div class="yamm">
            <div class="navbar-collapse collapse">
                <div class="container">
                    <!-- ============================================================= LOGO ============================================================= -->
                    <a class="navbar-brand" href="<?=$this->url()?>"><img src="<?= $this->basePath("assets-vodka-everest/images/logo.svg")?>" class="logo" alt=""></a>
                    <!-- ============================================================= LOGO : END ============================================================= -->
                   <!-- ============================================================= MAIN NAVIGATION ============================================================= -->
                    <ul class="nav navbar-nav">

                        <li><a href="<?=$this->url('drinks')?>">Home</a></li>
                        <li><a href="<?=$this->url('drinks')?>">Drinks</a></li>
                        <li><a href="<?=$this->url('imprensa')?>">Imprensa</a></li>
                        <li><a href="<?=$this->url('novidades-eventos')?>">Novidades & Eventos</a></li>
                        <li><a href="<?=$this->url('contato')?>">Contato</a></li>

                        <li class="dropdown pull-right searchbox">
                            <a href="#" class="dropdown-toggle js-activated"><i class="icon-search"></i></a>

                            <div class="dropdown-menu">
                                <form id="search" class="navbar-form search" role="search">
                                    <input type="search" class="form-control" placeholder="Type to search">
                                    <button type="submit" class="btn btn-default btn-submit icon-right-open"></button>
                                </form>
                            </div><!-- /.dropdown-menu -->
                        </li><!-- /.searchbox -->

                    </ul><!-- /.nav -->
                    <!-- ============================================================= MAIN NAVIGATION : END ============================================================= -->
                </div><!-- /.container -->
            </div><!-- /.navbar-collapse -->
        </div><!-- /.yamm -->
    </div><!-- /.navbar -->
</header>

<!-- ============================================================= HEADER : END ============================================================= -->


<!-- ============================================================= MAIN ============================================================= -->

<main>
<?= $this->content ?>
</main>
<!-- ============================================================= FOOTER ============================================================= -->

<footer class="dark-bg">
    <div class="container inner">
        <div class="row">


            <div class="col-md-6 col-xs-12 inner">
                <h4>Get In Touch</h4>
                <p>Doloreiur quia commolu ptatemp dolupta oreprerum tibusam eumenis et consent accullignis dentibea
                    autem inisita.</p>
                <ul class="contacts">
                    <li><i class="icon-location contact"></i> 84 Street, City, State 24813</li>
                    <li><i class="icon-mobile contact"></i> +00 (123) 456 78 90</li>
                    <li><a href="#"><i class="icon-mail-1 contact"></i> info@reen.com</a></li>
                </ul><!-- /.contacts -->
            </div><!-- /.col -->

            <div class="col-md-6 col-xs-12 inner">
                <h4>Free updates</h4>
                <p>Conecus iure posae volor remped modis aut lor volor accabora incim resto explabo.</p>
                <form id="newsletter" class="form-inline newsletter" role="form">
                    <label class="sr-only" for="exampleInputEmail">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail"
                           placeholder="Enter your email address">
                    <button type="submit" class="btn btn-default btn-submit">Subscribe</button>
                </form>
            </div><!-- /.col -->

        </div><!-- /.row -->
    </div><!-- .container -->

    <div class="footer-bottom">
        <div class="container inner">
            <p class="pull-left">© 2014 REEN. All rights reserved.</p>
            <ul class="footer-menu pull-right">
                <li><a href="<?=$this->url()?>">Inicio</a></li>
                <li><a href="<?=$this->url('sobre-nos')?>">Sobre Nos</a></li>
                <li><a href="<?=$this->url('politica-de-privacidade')?>">Politica De Privacidade</a></li>
                <li><a href="<?=$this->url('termos-de-uso')?>">Termos de Uso</a></li>
                <li><a href="<?=$this->url('declaracao-de-responsabilidade')?>">Declaração De Responsabilidade</a></li>
            </ul><!-- .footer-menu -->
        </div><!-- .container -->
    </div><!-- .footer-bottom -->
</footer>
<!-- END FAQ -->
<!-- JavaScripts placed at the end of the document so the pages load faster -->

<!-- Scripts -->
<?= $this->inlineScript()
    ->appendFile($this->basePath("assets-vodka-everest/js/jquery.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/jquery.easing.1.3.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/bootstrap.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/bootstrap-hover-dropdown.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/skrollr.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/skrollr.stylesheets.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/waypoints.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/waypoints-sticky.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/owl.carousel.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/jquery.isotope.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/jquery.easytabs.min.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/jquery.slickforms.js"))
    //->appendFile($this->basePath("assets-vodka-everest/js/google.maps.api.v3.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/viewport-units-buggyfill.js"))
    ->appendFile($this->basePath("assets-vodka-everest/js/scripts.js"))
?>

</body>
</html>
