<div class="box box-primary">
    <div class="box-body box-profile">
        <img id="cover-default" class="img-responsive"
             src="<?=$this->url(sprintf("%s/default", $this->route), ['controller'=>$this->controller,'action'=>'file'],
			['query'=>['name'=>$this->field->getValue(), 'thumbnail'=>true,'w'=>520]]);?>" alt="<?=$this->translate("No Imagem")?>">
		<?=$this->formRow($this->field->setLabel("")->setAttribute('id','cover'));?>

        <a href="<?=$this->url("adm-upload",[],[
                        'query'=>[
                            'assets'=>$this->controller,
                            'parent'=>$this->id
                        ]
        ])?>" class="btn btn-primary btn-block  <?=$this->id?'upload-modal':'disabled';?>">
            <i class="fa fa-file-image-o"></i> <b><?=$this->translate("Selecionar Imagem")?></b>
        </a>
    </div>
    <!-- /.box-body -->
</div>