<div class="input-group input-group-lg" id="dataTable_filter" style="width: 150px;margin-right: 10px">
    <input name="table_search" aria-controls="dataTable" class="quick-search form-control pull-right" placeholder="Search" type="text" value="<?=$this->quickSearch?>">
    <div class="input-group-btn">
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
    </div>
</div>