<div class="register-box">
	<div class="register-logo">
	<a href="<?=$this->url('home')?>"><b>Admin</b>LTE</a>
</div>

<div class="register-box-body">
	<p class="login-box-msg">Formulario de cadastro</p>
	<div id="formContainer">

    </div>
	<?=$this->ZfForm()->form();?>
	<div class="social-auth-links text-center">
		<p>- OR -</p>
	</div>

	<a href="<?=$this->url('auth')?>" class="text-center">Ja sou cadastrado</a>
</div>
<!-- /.form-box -->
</div>