<?=$this->partial('partial/form-error',['form'=>$this->form]);?>
<?=$this->form()->openTag($this->form->setAttribute('action',$this->url('auth/default', [
	'controller'=>'auth',
	'action'=>'register-form'
]))->setAttribute('name', 'AjaxForm'));?>
    	<?=$this->partial(sprintf('partial/%s/form/input-form-group', LAYOUT),[
    	        'field'=>$this->form->get('first_name')->setLabel("")
        ]);?>
        <?=$this->partial(sprintf('partial/%s/form/input-form-group', LAYOUT),[
            'field'=>$this->form->get('last_name')->setLabel("")
        ]);?>
        <?=$this->partial(sprintf('partial/%s/form/input-form-group', LAYOUT),[
            'field'=>$this->form->get('email')->setLabel("")
        ]);?>
        <?=$this->partial(sprintf('partial/%s/form/input-form-group', LAYOUT),[
            'field'=>$this->form->get('password')->setLabel("")
        ]);?>
    <div class="row">
        <!-- /.col -->
        <div class="col-xs-12">
            <?=$this->formSubmit($this->form->get('submit')->setValue('Criar Conta'));?>
         </div>
        <!-- /.col -->
    </div>
	<?=$this->form()->closeTag();?>
<?=$this->partial('partial/messages');?>