<?php
$collums12[] =  $this->El()->hidden('id')->hidden('empresa')->hidden('event_id')
    ->input('title')
    ->render($this->html('div')->setClass('row'));

$collums12[] = $this->El()->setClass('col-md-6')
    ->input('client')
    ->input('author')
    ->render($this->html('div')->setClass('row'));

$collums12[] = $this->El()->setClass('col-md-6')
    ->timepicker('start')
    ->timepicker('end')
    ->render($this->html('div')->setClass('row'));


$collums12[] = $this->El()->setClass('col-md-4')
    ->timepicker('created_at')
    ->timepicker('updated_at')
    ->input('status')
    ->render($this->html('div')->setClass('row'));

$collums12[] = $this->El()->input('description')->render($this->html('div')->setClass('row'));


$html[] = $this->html('div')->setClass('row')->setText(
    $this->html('div')->setClass('col-md-12 col-xs-12')->setText( implode("", $collums12))
);


$actions[] =   $this->Actions()
    ->submit()
    ->save_copy()
    ->save_close()
    ->back()
    ->render($this->html('div')->setClass('row'));
?>

<?= $this->partial(sprintf("/layout/%s/partial/create", LAYOUT), [
    'body' => implode("", $html),
    'actions' => implode("", $actions),
    'form' => $this->form,
    'route' => $this->route,
    'controller' => $this->controller,
]); ?>