<?= $this->partial(sprintf("partial/%s/top-navigation", LAYOUT),[
    'a'=>"Admin",'b'=>$this->route,'c'=>$this->controller,'d'=>"Makes", "e"=>'editar']); ?>
<?=$this->Tab()->setInfoTitle("Manutenção do Make")->tabPanel(
    $this->html('div')->setClass('col-md-12')->setText($this->html('div'))->appendText($this->render("form"))
)->nav("Geral")->render($this->html('section')->setClass('content'));