<?=$this->partial('partial/form-error',['form'=>$this->form]);?>
<?=$this->form()->openTag($this->form->setAttribute('action',$this->url(sprintf("%s/default", $this->route), [
    'controller'=>$this->controller,
    'action'=>'gerar-form'
]))->setAttribute('name','AjaxForm')->setAttribute('class',''));?>
<?=$this->html('div')->setClass('panel panel-default')->setText(
    $this->html('div')->setClass('panel-body')->setText(
        $this->html('div')->setClass('row')->setText(
            $this->html('div')->setClass('col-xs-12')->setText(
                $this->El()->hidden('id')->hidden('empresa')
                    ->input('name')
                    ->render($this->html('div')->setClass('row'))
            )->appendText(
                $this->El()->setClass('col-md-4')
                    ->input('route')
                    ->input('controller')
                    ->input('alias')
                    ->render($this->html('div')->setClass('row'))
            )->appendText(
                $this->El()->input('description')->render($this->html('div')->setClass('row'))
            )
        )
    )
)->appendText(
//ADD PANEL FOOTER
    $this->html('div')->setClass('panel-footer')->setText(
        $this->Actions()
            ->submit()
            ->back()
            ->render($this->html('div')->setClass('row'))
    )
);?>
<?=$this->form()->closeTag();?>
<?=$this->partial(sprintf('layout/%s/partial/messages', LAYOUT));?>
