<?php
$collums12[] = $this->El()->hidden('id')->hidden('empresa')->hidden('created_at')
    ->hidden('updated_at')
    ->hidden('path')
    ->hidden('assets')
    ->hidden('cover')
    ->hidden('status')
    ->hidden('parent')
    ->input('name')
    ->render($this->html('div')->setClass('row'));
$collums12[] = $this->El()->input('description')->render($this->html('div')->setClass('row'));

$actions[] = $this->Actions()
     ->save_gallery()
    ->render($this->html('div')->setClass('col-md-6 col-xs-12'));

$actions[] = $this->Actions()
    ->save_gallery($this->url("adm-admin/default",[
        'controller'=>'gallery',
        'action'=>'remove',
        'id'=>'id'
    ]))
    ->render($this->html('div')->setClass('col-md-6 col-xs-12'));

echo $this->html('div')->setClass('card m-b-0')->setText(
    $this->html('img')->setAttributes([
        'class' => 'card-img-top img-fluid',
        'src' => 'assets_images',
        'alt' => 'assets_images'
    ])
)->appendText(
//ADD PANEL FOOTER
    $this->html('div')->setClass('card-body')->setText(
        $this->html('div')->setClass('row')->setText(
            implode("", $actions)
        )
    )
);?>

<?= $this->partial(sprintf('layout/%s/partial/messages', LAYOUT)); ?>