<?php
$collums12[] = $this->El()->hidden('id')->hidden('empresa')->hidden('created_at')
    ->hidden('updated_at')
    ->hidden('path')
    ->hidden('assets')
    ->hidden('cover')
    ->hidden('status')
    ->hidden('parent')
    ->input('name')
    ->render($this->html('div')->setClass('row'));
$collums12[] = $this->El()->input('description')->render($this->html('div')->setClass('row'));

$actions[] = $this->Actions()
     ->save_gallery()
    ->render($this->html('div')->setClass('col-md-6 col-xs-12'));

$actions[] = $this->Actions()
    ->delete($this->url("adm-admin/default",[
        'controller'=>'gallery',
        'action'=>'remove',
        'id'=>'id'
    ]))
    ->render($this->html('div')->setClass('col-md-6 col-xs-12'));

echo $this->html('div')->setClass('card m-b-0')->setText(
    $this->html('img')->setAttributes([
        'class' => 'card-img-top img-fluid',
        'src' => 'assets_images',
        'alt' => 'assets_images'
    ])
)->appendText(
    $this->html('div')->setClass('card-body')->setText(
        implode("", $collums12)
    )->appendText(
        $this->html('div')->setAttributes([
            'class' => 'progress',
        ])->setText(
            $this->html('div')->setAttributes([
                'id' => 'upload-progress',
                'class' => 'progress-bar progress-bar-primary progress-bar-striped',
                'role' => 'progressbar',
                'aria-valuenow' => '40',
                'aria-valuemin' => '0',
                'aria-valuemax' => '100',
            ])->setText($this->html('span')->setAttributes([
                'class' => 'percent',
                'style' => "min-width: 2em;"
            ])->setText(''))
        )
    )
)->appendText(
//ADD PANEL FOOTER
    $this->html('div')->setClass('card-body')->setText(
        $this->html('div')->setClass('row')->setText(
            implode("", $actions)
        )
    )
);?>

<?= $this->partial(sprintf('layout/%s/partial/messages', LAYOUT)); ?>