<?php
if (!$this->form->get("author")->getValue()) {
    $this->form->get("author")->setValue($this->identity()->getId());
}
$collums08[] =  $this->El()->hidden('id')->hidden('empresa')->hidden('author')
    ->setClass('col-md-5')
    ->input('parent')
    ->setClass('col-md-7')
    ->input('code')
    ->render($this->html('div')->setClass('row'));

$collums08[] =  $this->El()
    ->input('name')
    ->render($this->html('div')->setClass('row'));

$collums08[] =  $this->El()
    ->setClass('col-md-4')
    ->input('costs')
    ->input('marge')
    ->input('price')
    ->render($this->html('div')->setClass('row'));
$collums08[] =  $this->El()
    ->setClass('col-md-3')
    ->input('width')
    ->input('height')
    ->input('weight')
    ->input('greeting')
    ->render($this->html('div')->setClass('row'));

$collums08[] = $this->El()->input('description')->render($this->html('div')->setClass('row'));

$collums04[] =   $this->html('div')->setClass('row')->setText(
    $this->El()->file()->render($this->html('div')->setClass('col-xs-12'))
);

$collums04[] = $this->El()
    ->timepicker('created_at')
    ->timepicker('updated_at')
    ->input('status')
    ->render($this->html('div')->setClass('row'));


$html[] = $this->html('div')->setClass('row')->setText(
    $this->html('div')->setClass('col-md-8 col-sm-12')->setText( implode("", $collums08))
)->appendText( $this->html('div')->setClass('col-md-4 col-sm-12')->setText( implode("", $collums04)));

$actions[] =   $this->Actions()
    ->submit()
    ->save_copy()
    ->save_close()
    ->back()
    ->render($this->html('div')->setClass('row'));
?>

<?= $this->partial(sprintf("/layout/%s/partial/create", LAYOUT), [
    'body' => implode("", $html),
    'actions' => implode("", $actions),
    'form' => $this->form,
    'route' => $this->route,
    'controller' => $this->controller,
]); ?>