<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle(getenv('ADMIN_NAME'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('landing/css/style.css'))
        ->prependStylesheet($this->basePath('landing/css/themify-icons.css'))
        ->prependStylesheet($this->basePath('landing/css/animate.css'))
        ->prependStylesheet($this->basePath('landing/css/bootstrap.min.css'))
        ->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,300,600')
        ->prependStylesheet('//fonts.googleapis.com/css?family=Roboto:400,300,500')
    ?>
</head>
<body>
<!-- Pre-loader -->
<div class="preloader">
    <div class="status">&nbsp;</div>
</div>

<div class="tagline">
    <div class="container">
        <div class="float-left">
            <div class="phone">
                <i class=" ti-mobile"></i> +1 800 123 45 67
            </div>
            <div class="email">
                <a href="mailto:#">
                    <i class=" ti-email"></i> support@mail.com
                </a>
            </div>
        </div>
        <div class="float-right">
            <ul class="top_socials">
                <li><a href="javascript:void(0);"><i class=" ti-facebook"></i></a></li>
                <li><a href="javascript:void(0);"><i class=" ti-skype"></i></a></li>
                <li><a href="javascript:void(0);"><i class=" ti-twitter-alt"></i></a></li>
                <li><a href="javascript:void(0);"><i class=" ti-github"></i></a></li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand logo" href="#">Minton</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07"
                aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#how-it-work">How it work</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#features">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#pricing">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#faq">FAQ</a>
                </li>
            </ul>

        </div>
    </div>
</nav>
<?= $this->content ?>
<!-- END FAQ -->

<footer class="footer bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <p class="copyright">2017 © Minton.</p>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</footer>
<!-- Scripts -->
<?= $this->inlineScript()
    ->prependFile($this->basePath('landing/js/jquery.app.js'))
    ->prependFile($this->basePath('landing/js/jquery.counterup.min.js'))
    ->prependFile($this->basePath('landing/js/jquery.waypoints.min.js'))
    ->prependFile($this->basePath('landing/js/wow.min.js'))
    ->prependFile($this->basePath('landing/js/SmoothScroll.js'))
    ->prependFile($this->basePath('landing/js/jquery.easing.1.3.min.js'))
    ->prependFile($this->basePath('landing/js/bootstrap.min.js'))
    ->prependFile($this->basePath('landing/js/popper.min.js'))
    ->prependFile($this->basePath('landing/js/jquery.min.js'))
?>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('.counter').counterUp({
            delay: 100,
            time: 1200
        });
    });
</script>

</body>
</html>
