<div class="params-wrap">
    <input type="hidden"  name="zfTableStatus" value="<?php echo $this->zfTableStatus?>" />
    <input type="hidden"  name="zfTablePage" value="<?php echo $this->zfTablePage?>" />
    <input type="hidden"  name="zfTableColumn" value="<?php echo $this->zfTableColumn?>" />
    <input type="hidden"  name="zfTableOrder" value="<?php echo $this->zfTableOrder?>" />
    <input type="hidden"  name="zfTableQuickSearch" value="<?php echo $this->zfTableQuickSearch?>" />
    <input type="hidden"  name="zfTableItemPerPage" value="<?php echo $this->zfTableItemPerPage?>" />
    <input type="hidden"  name="zfTableStartDate" value="<?php echo $this->zfTableStartDate?>" />
    <input type="hidden"  name="zfTableEndDate" value="<?php echo $this->zfTableEndDate?>" />
    <?php if($this->rowAction):?>
        <a href="<?php echo $this->rowAction?>" class="rowAction"></a>
    <?php endif;?>
</div>
