<?php
$collums08[] = $this->El()->hidden('id')->hidden('empresa')
    ->hidden('facebook')
    ->hidden('google')
    ->hidden('twitter')
    ->hidden('created_at')
    ->hidden('updated_at')
    ->hidden('description')
    ->setClass('col-md-6 col-xs-12')
    ->input('first_name')
    ->input('last_name')
    ->render($this->html('div')->setClass('row'));

$collums08[] = $this->El()
    ->setClass('col-md-6 col-xs-12')
    ->input('email')
    ->input('document')
    ->render($this->html('div')->setClass('row'));

$collums08[] = $this->El()
    ->setClass('col-md-6 col-xs-12')
    ->input('phone')
    ->input('password')
    ->render($this->html('div')->setClass('row'));


//$collums08[] = $this->El()
//    ->setClass('col-md-4 col-xs-12')
//    ->input('facebook')
//    ->input('google')
//    ->input('twitter')
//    ->render($this->html('div')->setClass('row'));


$collums04[] =   $this->html('div')->setClass('row')->setText(
    $this->El()->file()->render($this->html('div')->setClass('col-md-12'))
);
//
//$collums04[] = $this->El()->setClass('col-md-12')
//    ->input('created_at')
//    ->render($this->html('div')->setClass('row'));
//$collums04[] = $this->El()->setClass('col-md-12')
//    ->input('updated_at')
//    ->render($this->html('div')->setClass('row'));

$html[] = $this->html('div')->setClass('row')->setText(
    $this->html('div')->setClass('col-md-8 col-xs-12')->setText(implode("", $collums08))
)->appendText(
    $this->html('div')->setClass('col-md-4 col-xs-12')->setText(implode("", $collums04))
);
$actions[] =   $this->Actions()
    ->submit(12)
    ->render($this->html('div')->setClass('row'));
?>

<?= $this->partial(sprintf("/layout/%s/partial/create", LAYOUT), [
    'body' => implode("", $html),
    'actions' => implode("", $actions),
    'action' => 'profile',
    'form' => $this->form,
    'route' => $this->route,
    'controller' => $this->controller,
]); ?>

