<?=$this->partial('partial/form-error',['form'=>$this->form]);?>
<?=$this->form()->openTag($this->form->setAttribute('action',$this->url('auth/default', [
	'controller'=>'auth',
	'action'=>'register-form'
])));?>
    <h1>Create Account</h1>
<?=$this->partial(sprintf('partial/%s/form/input-form-group', LAYOUT),[
	'field'=>$this->form->get('first_name')->setLabel("")
]);?>
<?=$this->partial(sprintf('partial/%s/form/input-form-group', LAYOUT),[
	'field'=>$this->form->get('last_name')->setLabel("")
]);?>
<?=$this->partial(sprintf('partial/%s/form/input-form-group', LAYOUT),[
	'field'=>$this->form->get('email')->setLabel("")
]);?>
<?=$this->partial(sprintf('partial/%s/form/input-form-group', LAYOUT),[
	'field'=>$this->form->get('password')->setLabel("")
]);?>
    <div class="row">
        <!-- /.col -->
        <div class="col-xs-12">
			<?=$this->formSubmit($this->form->get('submit')->setValue('Criar Conta')->setAttribute('style','margin-left:0'));?>
        </div>
        <!-- /.col -->
    </div>
    <div class="clearfix"></div>
    <div class="separator">
        <p class="change_link">Already a member ?
            <a href="<?=$this->url('auth/default', [
				'controller'=>'auth',
				'action'=>'login'
			])?>" class="to_register"> Log in </a>
        </p>

        <div class="clearfix"></div>
        <br />

        <div>
            <h1><i class="fa fa-paw"></i> Gentelella Alela!</h1>
            <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
        </div>
    </div>
<?=$this->form()->closeTag();?>
<?=$this->partial('partial/messages');?>