<?php
/**
 * Created By: Claudio  Campos
 * E-Mail: callcocam@gmail.com
 */
namespace Admin\Service;


use Admin\Entity\ResourceEntity;
use Admin\Entity\RoleEntity;
use Core\Service\AbstractService;
use Doctrine\ORM\EntityManager;

class GroupService extends AbstractService
{

    /**
     * NameService constructor.
     * @param EntityManager $em
     */
    public function __construct(EntityManager $em)
    {
        $this->entity="Admin\Entity\GroupEntity";
        parent::__construct($em);
    }

    public function save( Array $data = [] )
    {
        $data['route'] = $this->em->getReference(ResourceEntity::class, $data['route']);
        $data['role'] = $this->em->getReference(RoleEntity::class, $data['role']);
        return parent::save($data); // TODO: Change the autogenerated stub
    }
}