<?php
/**
 * Created By: Claudio  Campos
 * E-Mail: callcocam@gmail.com
 */
namespace Admin\Service;


use Core\Service\AbstractService;
use Doctrine\ORM\EntityManager;

class UserService extends AbstractService
{

    /**
     * NameService constructor.
     * @param EntityManager $em
     */
    public function __construct(EntityManager $em)
    {
        $this->entity="Admin\Entity\UserEntity";
        parent::__construct($em);
    }
    public function save(Array $data = [])
    {
        if(empty($data['password'])):
            unset($data['password']);
            else:
                $data['password'] = $this->encryptPassword($data['email'],$data['password']);
        endif;
        return parent::save($data); // TODO: Change the autogenerated stub
    }
}