<div class="wrapper-page">
    <div class="text-center">
        <a href="/" class="logo-lg"><i class="mdi mdi-radar"></i> <span>Minton</span> </a>
    </div>
    <div>
        <?=$this->render("login-form",[
            'form'=>$this->form,
            'route'=>$this->route,
            'controller'=>$this->controller,
        ]);?>
    </div>

</div>
<script>
    var resizefunc = [];

</script>

