<?php
/**
 * Created By: Claudio  Campos
 * E-Mail: callcocam@gmail.com
 */

namespace Agenda\Service;


use Admin\Entity\ClientEntity;
use Agenda\Entity\EventoEntity;
use Core\Service\AbstractService;
use Doctrine\ORM\EntityManager;

class EventoService extends AbstractService
{

    /**
     * NameService constructor.
     * @param EntityManager $em
     */
    public function __construct( EntityManager $em )
    {
        $this->entity = "Agenda\Entity\EventoEntity";
        parent::__construct($em);
    }

    public function save( Array $data = [] )
    {
        $data['client'] = $this->em->getReference(ClientEntity::class, $data['client']);
        $data['event_id'] = $this->em->getReference(EventoEntity::class, $data['event_id']);
        if (isset($data['start']) && $data['start']) {
            $data['start'] = new \DateTime ($this->Data($data['start']));
        } else {
            $data['start'] = new \DateTime (date("Y-m-d H:m"));
        }
        if (isset($data['end']) && $data['end']) {
            $data['end'] = new \DateTime ($this->Data($data['end']));
        } else {
            $data['end'] = new \DateTime (date("Y-m-d H:m"));
        }
        return parent::save($data); // TODO: Change the autogenerated stub
    }
}