<div class="form-group ">
    <label for="<?= $this->field->getAttribute('id') ?>"><?= $this->translate($this->field->getLabel()) ?></label>
    <div class="input-group input-group-lg date">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-calendar"></i></span>
        </div>
        <?=$this->formRow($this->field->setLabel(''));?>
    </div>
    <!-- /.input group -->
</div>