<?php

$collums12[] =  $this->El()->hidden('id')->hidden('empresa')->hidden('created_at')->hidden('updated_at')
    ->input('title')
    ->render($this->html('div')->setClass('row'));

$collums12[] =  $this->El()
    ->input('class_name')
    ->render($this->html('div')->setClass('row'));

$collums12[] = $this->El()
    ->input('status')
    ->render($this->html('div')->setClass('row'));

$collums12[] = $this->El()->input('description')->render($this->html('div')->setClass('row'));


$html[] = $this->html('div')->setClass('row')->setText(
    $this->html('div')->setClass('col-md-12 col-xs-12')->setText( implode("", $collums12))
);

$actions[] = $this->Actions()
    ->dismiss(5)
    ->upload(7)
    ->render($this->html('div')->setClass('row'));
?>

<?= $this->partial(sprintf("/layout/%s/partial/modal-default", LAYOUT), [
    'body' => implode("", $html),
    'actions' => implode("", $actions),
    'form' => $this->form,
    'title' => "Criar Evento",
    'route' => $this->route,
    'controller' => $this->controller,
]); ?>