<div class="item"
     style="background-image: url(<?= $this->basePath($this->cover)?>);">
    <div class="container">
        <div class="caption vertical-center text-center">
            <h1 class="fadeInDown-1 light-color">{name}</h1>
            <p class="fadeInDown-2 medium-color">{preview}</p>
            <div class="fadeInDown-3">
                <a href="{url}" class="btn btn-large">Get started now</a>
            </div><!-- /.fadeIn -->
        </div><!-- /.caption -->
    </div><!-- /.container -->
</div><!-- /.item -->