<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->headTitle(sprintf("%s-Login", getenv('ADMIN_NAME')))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('assets-admin/css/style-default.css'))
        ->prependStylesheet($this->basePath('assets-admin/css/toastr.min.css'))
        ->prependStylesheet($this->basePath('green-vertical/css/style.css'))
        ->prependStylesheet($this->basePath('green-vertical/css/icons.css'))
        ->prependStylesheet($this->basePath('green-vertical/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('green-vertical/plugins/switchery/switchery.min.css'))
    ?>
    <?= $this->headScript()->appendFile(
        'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
        'text/javascript',
        ['conditional' => 'lt IE 9']
    )->appendFile(
        'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
        'text/javascript',
        ['conditional' => 'lt IE 9']
    )
        ->prependFile($this->basePath('assets-admin/js/jquery.form.min.js'))
        ->prependFile($this->basePath('assets-admin/plugins/iCheck/icheck.min.js'))
        ->prependFile($this->basePath('green-vertical/js/bootstrap.min.js'))
        ->prependFile($this->basePath('green-vertical/js/popper.min.js'))
        ->prependFile($this->basePath('assets-admin/js/jquery.form.min.js'))
        ->prependFile($this->basePath('green-vertical/js/jquery.min.js'))
        ->prependFile($this->basePath('green-vertical/js/modernizr.min.js'))
    ?>

</head>
<body>
<!-- Content Wrapper. Contains page content -->
<?= $this->content ?>
<!--------------------------
  | Your Page Content Here |
-------------------------->
<!-- /.content-wrapper -->
<!-- ./wrapper -->

<?= $this->inlineScript() ->appendFile($this->basePath('assets-admin/js/form.init.js'))
    ->prependFile($this->basePath('assets-admin/js/zf-alert.js'))
    ->prependFile($this->basePath('assets-admin/js/toastr.min.js'))

?>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });

    });
</script>
<?=$this->partial('partial/messages');?>
<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>