<?= $this->doctype() ?>
<?php // Within your view
date_default_timezone_set('America/Sao_Paulo');
$this->plugin('dateFormat')
    ->setTimezone('America/Sao_Paulo')
    ->setLocale('pt_BR');  ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(getenv('ADMIN_NAME'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('admin-lte/css/skins/skin-blue.min.css'))
            ->prependStylesheet($this->basePath('admin-lte/css/AdminLTE.min.css'))
             ->prependStylesheet($this->basePath('admin-lte/css/ionicons.min.css'))
            ->prependStylesheet($this->basePath('admin-lte/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('admin-lte/css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?= $this->headScript()->appendFile(
                'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
                'text/javascript',
                ['conditional' => 'lt IE 9']
            )->appendFile(
                'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
                'text/javascript',
                ['conditional' => 'lt IE 9']
            )
             ->prependFile($this->basePath('admin-lte/js/adminlte.min.js'))
            ->prependFile($this->basePath('admin-lte/js/bootstrap.min.js'))
            ->prependFile($this->basePath('admin-lte/js/jquery.min.js'))
        ?>
        <!--
     BODY TAG OPTIONS:
     =================
     Apply one or more of the following classes to get the
     desired effect
     |---------------------------------------------------------|
     | SKINS         | skin-blue                               |
     |               | skin-black                              |
     |               | skin-purple                             |
     |               | skin-yellow                             |
     |               | skin-red                                |
     |               | skin-green                              |
     |---------------------------------------------------------|
     |LAYOUT OPTIONS | fixed                                   |
     |               | layout-boxed                            |
     |               | layout-top-nav                          |
     |               | sidebar-collapse                        |
     |               | sidebar-mini                            |
     |---------------------------------------------------------|
     -->
    <body class="hold-transition skin-blue">
       <div class="wrapper">
            <!-- Content Wrapper. Contains page content -->

                    <?= $this->content ?>
                   <!-- /.content -->
           </div>
           <!-- /.content-wrapper -->

           <!-- Main Footer -->
           <footer class="main-footer">
               <!-- To the right -->
               <div class="pull-right hidden-xs">
                   Anything you want
               </div>
               <!-- Default to the left -->
               <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
           </footer>
           <!-- /.control-sidebar -->
           <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
       </div>

    </body>
</html>
