<?php

namespace Admin\Repository;

use Core\Entity\AbstractRepository;
use Zend\Debug\Debug;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends AbstractRepository
{

   public function findByAll()
   {
       Debug::dump(get_class($this));die;
       $sql = $this->createQueryBuilder('genus');
       $sql->where($sql->expr()->eq('genus.status',1));
       return $sql->getQuery()->getResult();
   }


}
