<?= $this->doctype() ?>
<?php // Within your view
date_default_timezone_set('America/Sao_Paulo');
$this->plugin('dateFormat')
    ->setTimezone('America/Sao_Paulo')
    ->setLocale('pt_BR');
$acl = $this->Acl()->getAcl()
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(getenv('ADMIN_NAME'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
         <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('assets-admin/css/zf-table.css'))
            ->prependStylesheet($this->basePath('assets-admin/css/toastr.min.css'))
            ->prependStylesheet($this->basePath('assets-admin/plugins/bootstrap-timerpicker/css/bootstrap-datepicker.min.css'))
            ->prependStylesheet($this->basePath('assets-admin/plugins/bootstrap-daterangepicker/css/daterangepicker.css'))
            ->prependStylesheet($this->basePath('assets-admin/css/jquery-confirm.min.css'))
            ->prependStylesheet($this->basePath('assets-admin/plugins/iCheck/square/_all.css'))
            ->prependStylesheet($this->basePath('assets-admin/css/ionicons.css'))
            ->prependStylesheet($this->basePath('assets-admin/css/font-awesome.css'))
             ->prependStylesheet($this->basePath('admin-lte/css/skins/_all-skins.min.css'))
            ->prependStylesheet($this->basePath('admin-lte/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('admin-lte/css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()->appendFile(
            'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
            'text/javascript',
            ['conditional' => 'lt IE 9']
        )->appendFile(
            'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
            'text/javascript',
            ['conditional' => 'lt IE 9']
        )
            ->appendFile($this->basePath('assets-admin/js/form.init.js'))
            ->prependFile($this->basePath('assets-admin/js/zf-alert.js'))
            ->prependFile($this->basePath('assets-admin/js/zf-table.js'))
            ->prependFile($this->basePath('assets-admin/js/toastr.min.js'))
            ->prependFile($this->basePath('assets-admin/js/formatCurrency.js'))
            ->prependFile($this->basePath('assets-admin/plugins/bootstrap-timerpicker/locales/bootstrap-datepicker.pt-BR.min.js'))
            ->prependFile($this->basePath('assets-admin/plugins/bootstrap-timerpicker/js/bootstrap-datepicker.min.js'))
            ->prependFile($this->basePath('assets-admin/plugins/bootstrap-daterangepicker/js/daterangepicker.js'))
            ->prependFile($this->basePath('assets-admin/plugins/moment/locale/pt-br.js'))
            ->prependFile($this->basePath('assets-admin/plugins/moment/moment.js'))
            ->prependFile($this->basePath('assets-admin/js/jquery-confirm.min.js'))
            ->prependFile($this->basePath('assets-admin/js/upload.init.js'))
            ->prependFile($this->basePath('assets-admin/js/jquery.form.min.js'))
            ->prependFile($this->basePath('assets-admin/plugins/iCheck/icheck.min.js'))
            ->prependFile($this->basePath('admin-lte/js/adminlte.min.js'))
            ->prependFile($this->basePath('admin-lte/js/bootstrap.min.js'))
            ->prependFile($this->basePath('admin-lte/js/jquery.min.js'))
        ?>

        <!--
     BODY TAG OPTIONS:
     =================
     Apply one or more of the following classes to get the
     desired effect
     |---------------------------------------------------------|
     | SKINS         | skin-blue                               |
     |               | skin-black                              |
     |               | skin-purple                             |
     |               | skin-yellow                             |
     |               | skin-red                                |
     |               | skin-green                              |
     |---------------------------------------------------------|
     |LAYOUT OPTIONS | fixed                                   |
     |               | layout-boxed                            |
     |               | layout-top-nav                          |
     |               | sidebar-collapse                        |
     |               | sidebar-mini                            |
     |---------------------------------------------------------|
     -->
    <body class="skin-blue sidebar-mini sidebar-collapse">
       <div class="wrapper">
           <?=$this->partial(sprintf("layout/%s/partial/header", LAYOUT));?>
           <!-- Left side column. contains the logo and sidebar -->
           <?=$this->navigation('Navigation')->menu()->setAcl($acl)->setRole((string)$this->identity()->getAccess())->setPartial(sprintf("layout/%s/partial/sidebar", LAYOUT));?>
           <!-- Content Wrapper. Contains page content -->
           <div class="content-wrapper">
               <!-- Content Header (Page header) -->
               <?= $this->partial(sprintf("layout/%s/partial/top-navigation", LAYOUT),[
                   'a'=>"Admin",'b'=>$this->Route()->getRoute(),'c'=>$this->Route()->getController(),'d'=>"Privilege", "e"=>'editar']); ?>
               <!-- Main content -->
               <section class="content container-fluid">
                      <?= $this->content ?>
               </section>
               <!-- /.content -->
           </div>
           <!-- /.content-wrapper -->

           <!-- Main Footer -->
           <footer class="main-footer">
               <!-- To the right -->
               <div class="pull-right hidden-xs">
                   Anything you want
               </div>
               <!-- Default to the left -->
               <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
           </footer>

           <!-- Control Sidebar -->
           <?=$this->partial(sprintf("layout/%s/partial/config", LAYOUT));?>
           <!-- /.control-sidebar -->
           <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
           <div class="control-sidebar-bg"></div>
       </div>

    </body>
</html>
