<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->headTitle('AdminLTE 2 | Starter')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

        ->prependStylesheet('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic')
        ->prependStylesheet($this->basePath('admin-lte/css/toastr.min.css'))
        ->prependStylesheet($this->basePath('admin-lte/css/skins/skin-blue.min.css'))
        ->prependStylesheet($this->basePath('admin-lte/css/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('admin-lte/plugins/iCheck/square/_all.css'))
        ->prependStylesheet($this->basePath('admin-lte/css/ionicons.min.css'))
        ->prependStylesheet($this->basePath('admin-lte/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('admin-lte/css/bootstrap.min.css'))
    ?>

    <!-- REQUIRED JS SCRIPTS -->
    <?= $this->headScript()->appendFile(
        'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
        'text/javascript',
        ['conditional' => 'lt IE 9']
    )->appendFile(
        'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
        'text/javascript',
        ['conditional' => 'lt IE 9']
    )
        ->prependFile($this->basePath('admin-lte/js/toastr.min.js'))
        ->prependFile($this->basePath('admin-lte/js/jquery.form.min.js'))
        ->prependFile($this->basePath('admin-lte/plugins/iCheck/icheck.min.js'))
        ->prependFile($this->basePath('admin-lte/js/bootstrap.min.js'))
        ->prependFile($this->basePath('admin-lte/js/jquery.min.js'))
    ?>


</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition login-page">
<!-- Content Wrapper. Contains page content -->
<?= $this->content ?>
<!--------------------------
  | Your Page Content Here |
-------------------------->
<!-- /.content-wrapper -->
<!-- ./wrapper -->
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>
<div class="body-processing">
    <div class="processing">
    </div>
</div>
<?=$this->partial('partial/messages');?>
<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>