<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="<?=$this->url("admin")?>" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b><?= getenv('ADMIN_NAME_A') ?></b><?= getenv('ADMIN_NAME_LT') ?></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b><?= getenv('ADMIN_NAME') ?></b><?= getenv('ADMIN_NAME_ABR') ?></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->

                <!-- /.messages-menu -->

                <!-- Notifications Menu -->

                <!-- Tasks Menu -->

                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="<?= $this->basePath($this->identity()->getCover()) ?>" class="user-image"
                             alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">Alexander Pierce</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="<?= $this->basePath($this->identity()->getCover()) ?>" class="img-circle"
                                 alt="User Image">

                            <p>
                                <?= $this->identity()->getFirstName() ?> <?= $this->identity()->getLastName() ?> - Web
                                Developer
                                <small>Member
                                    since <?= $this->date()->LONG($this->identity()->getCreatedAt()->format("d-m-Y")) ?> </small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                            <!-- /.row -->
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="<?= $this->url("adm-admin/default", [
                                    'controller' => 'user',
                                    'action' => 'profile'
                                ]) ?>" class="btn btn-default btn-flat"><?= $this->translate('Profile') ?></a>
                            </div>
                            <div class="pull-right">
                                <a href="<?= $this->url("adm-auth-sair") ?>"
                                   class="btn btn-default btn-flat"><?= $this->translate('Sign out') ?></a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>