<div id="tableContainer"  style="position: relative;min-height: 500px">
    <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 85%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<script>
    $("#tableContainer").zfTable('<?=$this->url("adm-sisc/default",['controller'=>'anexo', 'action'=>'listar','id'=>$this->Route()->getId()],[
        'query'=>[
            'solicitacion'=>$this->Route()->getId()
        ]
    ])?>');
</script>