<?php

namespace S_Demo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * S_NameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class S_NameRepository extends EntityRepository
{
}
